apiVersion: v1
kind: Service
metadata:
  name: code-frequency-service
spec:
  selector:
    app: code-frequency-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080